/**
 * JeevanSetu Schema-Aligned Mock Datasets
 * Designed for pure frontend testing and demonstration across all roles.
 * Strictly educational and navigation data - no fake live claims.
 */

export const mockUsers = [
  {
    id: "usr-pat-01",
    name: "Rameshwar Patil",
    phone: "+91 98234 11204",
    role: "patient",
    district: "Gadchiroli",
    state: "Maharashtra",
    village: "Ashti",
    avatar: "RP",
  },
  {
    id: "usr-phc-01",
    name: "Dr. Ananya Deshmukh",
    role: "phc_staff",
    phcName: "Ashti Primary Health Centre",
    phcId: "phc-101",
    district: "Gadchiroli",
    designation: "Medical Officer / PHC In-Charge",
    avatar: "AD",
  },
  {
    id: "usr-doc-01",
    name: "Dr. Vivek Kulkarni",
    role: "doctor",
    hospitalName: "District Civil Hospital Gadchiroli",
    specialization: "General Medicine & Cardiology",
    avatar: "VK",
  },
  {
    id: "usr-hosp-01",
    name: "Rajesh Shinde",
    role: "hospital",
    hospitalName: "Government Medical College & Hospital Nagpur",
    designation: "Referral Desk Coordinator",
    avatar: "RS",
  },
  {
    id: "usr-ngo-01",
    name: "Sunita Gavit",
    role: "ngo",
    ngoName: "Gramin Arogya Sahayog Trust",
    focusArea: "Patient Transport & Financial Assistance",
    avatar: "SG",
  },
  {
    id: "usr-adm-01",
    name: "District Health Officer (DHO)",
    role: "admin",
    department: "Department of Public Health & Family Welfare",
    district: "Gadchiroli & Chandrapur",
    avatar: "DHO",
  },
];

export const mockPatientCases = [
  {
    id: "JVS-MH-7A82K1",
    legacyId: "case-2026-001",
    patientId: "usr-pat-01",
    patientName: "Rameshwar Patil",
    caregiverRelationship: "myself", // myself | family_member | dependent
    age: 52,
    gender: "Male",
    primarySymptoms: "Persistent chest tightness during exertion, breathlessness, chronic hypertension",
    vitals: { bp: "154/98 mmHg", pulse: "86 bpm", spo2: "96%", temp: "98.4 F" },
    initialDiagnosisImpression: "Suspected Ischemic Heart Disease with Grade 2 Hypertension",
    status: "active_referral",
    phcName: "Ashti Primary Health Centre",
    createdAt: "2026-08-18T09:30:00Z",
    updatedAt: "2026-08-21T14:15:00Z",
    documentsCount: 3,
    activeReferralId: "ref-9921",
    notes: "Requires echocardiogram and secondary cardiology evaluation. Local PHC stock for Atenolol is sufficient, but secondary tertiary referral needed.",
    assistancePathways: [
      {
        provider: "Ayushman Bharat PM-JAY",
        type: "Government Health Scheme",
        status: "Eligible & Pre-Authorized",
        coverageSummary: "100% Cashless secondary hospitalization and cardiology workup.",
        whyRelevant: "Patient SECC rural BPL category qualifies for empanelled district hospital care.",
      },
      {
        provider: "Gramin Arogya Sahayog Trust",
        type: "Verified NGO Grant",
        status: "Transit Grant Available",
        coverageSummary: "₹1,200 emergency patient van transit grant from Ashti to Gadchiroli.",
        whyRelevant: "Local NGO assistance fund covers distance-based rural ambulance costs.",
      },
    ],
  },
  {
    id: "JVS-MH-3B91P4",
    legacyId: "case-2026-002",
    patientId: "usr-pat-02",
    patientName: "Savita Bai Munde",
    caregiverRelationship: "family_member",
    age: 28,
    gender: "Female",
    primarySymptoms: "Severe anemia in 3rd trimester pregnancy, Hb 7.2 g/dL, pedal edema",
    vitals: { bp: "118/76 mmHg", pulse: "92 bpm", spo2: "98%", temp: "98.6 F" },
    initialDiagnosisImpression: "High-Risk Pregnancy (Severe Anemia)",
    status: "treatment_started",
    phcName: "Chamorshi Rural Hospital",
    createdAt: "2026-08-15T11:00:00Z",
    updatedAt: "2026-08-20T16:00:00Z",
    documentsCount: 4,
    activeReferralId: "ref-9874",
    notes: "IV Iron sucrose scheduled. Covered under Janani Shishu Suraksha Karyakram (JSSK).",
    assistancePathways: [
      {
        provider: "Janani Shishu Suraksha Karyakram (JSSK)",
        type: "Government Health Scheme",
        status: "Fully Covered",
        coverageSummary: "Free institutional delivery, medicines, diagnostic tests, and transport.",
        whyRelevant: "Universal entitlement for all institutional deliveries in government health centers.",
      },
    ],
  },
];

export const mockReferrals = [
  {
    id: "ref-9921",
    caseId: "JVS-MH-7A82K1",
    patientName: "Rameshwar Patil",
    patientAge: 52,
    patientGender: "Male",
    fromFacility: "Ashti Primary Health Centre",
    toFacility: "District Civil Hospital Gadchiroli",
    department: "Cardiology / Internal Medicine",
    priority: "high",
    currentStage: "accepted",
    currentStageLabel: "Accepted by Facility",
    createdAt: "2026-08-19T10:15:00Z",
    updatedAt: "2026-08-21T11:30:00Z",
    transportRequired: true,
    schemeAssistanceApplied: "Ayushman Bharat PM-JAY",
    steps: [
      { key: "created", label: "Created", date: "19 Aug 2026, 10:15 AM", completed: true, notes: "Initiated by Dr. Ananya Deshmukh" },
      { key: "notified", label: "Notified", date: "19 Aug 2026, 10:20 AM", completed: true, notes: "Digital alert sent to District Hospital Referral Desk" },
      { key: "accepted", label: "Accepted", date: "20 Aug 2026, 09:45 AM", completed: true, notes: "Confirmed by Dr. Vivek Kulkarni (Cardiology Desk)" },
      { key: "hospital_reached", label: "Hospital Reached", date: "Pending", completed: false, notes: "Patient scheduled to arrive on 24 Aug 2026" },
      { key: "treatment_started", label: "Treatment Started", date: "Pending", completed: false, notes: "Echocardiogram & specialist review" },
      { key: "completed", label: "Completed", date: "Pending", completed: false, notes: "Final summary & discharge sync" },
    ],
    travelChecklist: {
      referralSlipConfirmed: true,
      receivingFacilityStatus: "Doctor on duty & ICU beds confirmed",
      requiredDocuments: [
        { name: "JeevanSetu Referral Printout / Case ID (JVS-MH-7A82K1)", status: "required", ready: true },
        { name: "Aadhaar Card of Patient & Attendant", status: "required", ready: true },
        { name: "BPL Ration Card for Ayushman Bharat Counter", status: "required", ready: true },
        { name: "Previous PHC Prescription & Vitals Slip", status: "recommended", ready: true },
        { name: "Previous ECG Strip from Ashti PHC", status: "recommended", ready: false },
      ],
    },
  },
  {
    id: "ref-9874",
    caseId: "JVS-MH-3B91P4",
    patientName: "Savita Bai Munde",
    patientAge: 28,
    patientGender: "Female",
    fromFacility: "Chamorshi Rural Hospital",
    toFacility: "Sub-District Hospital Ballarpur",
    department: "Obstetrics & Gynecology",
    priority: "urgent",
    currentStage: "treatment_started",
    currentStageLabel: "Treatment Started",
    createdAt: "2026-08-16T08:30:00Z",
    updatedAt: "2026-08-20T16:00:00Z",
    transportRequired: true,
    schemeAssistanceApplied: "Janani Shishu Suraksha Karyakram",
    steps: [
      { key: "created", label: "Created", date: "16 Aug 2026, 08:30 AM", completed: true, notes: "High risk pregnancy referral" },
      { key: "notified", label: "Notified", date: "16 Aug 2026, 08:35 AM", completed: true, notes: "SMS & System push notification" },
      { key: "accepted", label: "Accepted", date: "16 Aug 2026, 09:10 AM", completed: true, notes: "Maternity bed reserved" },
      { key: "hospital_reached", label: "Hospital Reached", date: "17 Aug 2026, 11:00 AM", completed: true, notes: "108 Ambulance transit confirmed" },
      { key: "treatment_started", label: "Treatment Started", date: "17 Aug 2026, 01:30 PM", completed: true, notes: "IV Iron therapy in progress" },
      { key: "completed", label: "Completed", date: "Pending", completed: false, notes: "Expected post-delivery clearance" },
    ],
    travelChecklist: {
      referralSlipConfirmed: true,
      receivingFacilityStatus: "Maternity wing and SNCU beds available",
      requiredDocuments: [
        { name: "Mother-Child Protection (MCP) Card", status: "required", ready: true },
        { name: "Aadhaar Card", status: "required", ready: true },
        { name: "Hemoglobin & Blood Group Lab Reports", status: "required", ready: true },
        { name: "ANC Registration Slip", status: "recommended", ready: true },
      ],
    },
  },
];

export const mockHospitals = [
  {
    id: "hosp-001",
    name: "District Civil Hospital Gadchiroli",
    type: "Government District Hospital",
    careLevel: "district_hospital", // phc | chc | district_hospital | tertiary
    district: "Gadchiroli",
    state: "Maharashtra",
    distanceKm: 24.5,
    address: "Complex Area, Civil Lines, Gadchiroli, Maharashtra 442605",
    phone: "+91 7132 222144",
    emergencyHelpline: "108 / +91 7132 222100",
    isVerified: true,
    verifiedAt: "2026-01-10",
    specialties: ["General Medicine", "General Surgery", "Cardiology", "Orthopedics", "Pediatrics", "Obstetrics"],
    facilities: ["24x7 ICU", "Blood Bank", "Dialysis Unit", "Digital X-Ray", "CT Scan"],
    bedAvailability: { total: 250, available: 42, icuAvailable: 4 },
    schemesAccepted: ["Ayushman Bharat PM-JAY", "Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY)", "JSSK"],
    // Check Before You Travel Status
    travelStatus: {
      doctorStatus: "available", // available | limited | unavailable
      doctorStatusText: "Cardiologist & General Physicians on Duty",
      medicineStockStatus: "sufficient",
      medicineStatusText: "Essential IV fluids & cardiac emergency meds stocked",
      diagnosticStatus: "available",
      diagnosticStatusText: "ECG, Digital X-Ray, Blood Bank functional",
      referralAcceptanceStatus: "available",
      referralAcceptanceText: "Accepting general & cardiac referrals",
      lastVerified: "Today, 14:15 IST (Demo timestamp / PHC Staff reported)",
    },
    isTransplantCentre: true,
    transplantServices: ["Corneal Retrieval Centre", "Organ Pledge Registration Desk"],
  },
  {
    id: "hosp-002",
    name: "Sub-District Hospital Ballarpur",
    type: "Sub-District Hospital (SDH / CHC Level)",
    careLevel: "chc",
    district: "Chandrapur",
    state: "Maharashtra",
    distanceKm: 38.0,
    address: "Railway Station Road, Ballarpur, Maharashtra 442701",
    phone: "+91 7172 240212",
    emergencyHelpline: "108",
    isVerified: true,
    verifiedAt: "2026-02-15",
    specialties: ["Maternal & Child Health", "General Medicine", "Emergency Trauma"],
    facilities: ["Emergency Care", "Maternity Wing", "Pathology Lab", "SNCU"],
    bedAvailability: { total: 100, available: 19, icuAvailable: 2 },
    schemesAccepted: ["PM-JAY", "MJPJAY", "Pradhan Mantri Matru Vandana Yojana"],
    travelStatus: {
      doctorStatus: "available",
      doctorStatusText: "Gynecologist & Pediatrician Available",
      medicineStockStatus: "depleting",
      medicineStatusText: "IV Iron in stock; Metformin low",
      diagnosticStatus: "available",
      diagnosticStatusText: "Basic blood tests & Ultrasound active",
      referralAcceptanceStatus: "available",
      referralAcceptanceText: "Maternal & pediatric intake open",
      lastVerified: "Today, 13:30 IST (Demo timestamp / Hospital Desk reported)",
    },
    isTransplantCentre: false,
    transplantServices: [],
  },
  {
    id: "hosp-003",
    name: "Government Medical College & Hospital Nagpur",
    type: "Tertiary Teaching Hospital",
    careLevel: "tertiary",
    district: "Nagpur",
    state: "Maharashtra",
    distanceKm: 160.0,
    address: "Medical Square, Hanuman Nagar, Nagpur, Maharashtra 440003",
    phone: "+91 712 2744401",
    emergencyHelpline: "108 / +91 712 2744650",
    isVerified: true,
    verifiedAt: "2025-11-20",
    specialties: ["Super-speciality Cardiology", "Neurosurgery", "Oncology", "Nephrology", "Pediatric Surgery"],
    facilities: ["Advanced Cardiac Cath Lab", "Multi-slice MRI", "Burn Unit", "Advanced NICU/PICU", "Renal Transplant Unit"],
    bedAvailability: { total: 1400, available: 110, icuAvailable: 12 },
    schemesAccepted: ["Ayushman Bharat PM-JAY", "MJPJAY", "Rashtriya Arogya Nidhi (RAN)"],
    travelStatus: {
      doctorStatus: "available",
      doctorStatusText: "Full super-specialty departments active",
      medicineStockStatus: "sufficient",
      medicineStatusText: "Complete tertiary formulary stocked",
      diagnosticStatus: "available",
      diagnosticStatusText: "MRI, CT, Cath Lab, Dialysis operational",
      referralAcceptanceStatus: "available",
      referralAcceptanceText: "Requires authorized district hospital referral slip",
      lastVerified: "Today, 12:00 IST (Demo timestamp / Central Administration)",
    },
    isTransplantCentre: true,
    transplantServices: ["Authorized Kidney Transplant Centre", "Cornea Bank", "State SOTTO Nodal Unit"],
  },
];

export const mockSchemes = [
  {
    id: "sch-001",
    name: "Ayushman Bharat PM-JAY",
    fullName: "Pradhan Mantri Jan Arogya Yojana",
    category: "Health Insurance / Cashless Treatment",
    maxCoverage: "₹5,00,000 per family per year",
    eligibilitySummary: "Families identified in SECC 2011 rural database, Antyodaya Anna Yojana (AAY) ration cardholders.",
    coveredTreatments: "Secondary and tertiary hospitalizations, cardiac procedures, oncology, trauma surgery.",
    documentsRequired: ["Aadhaar Card", "Ration Card (BPL/AAY)", "Ayushman Card or Mobile Number"],
    howToApply: "Available directly at all empaneled PHCs, Civil Hospital Ayushman Mitra desks, or online at NHA portal.",
    portalUrl: "https://beneficiary.nha.gov.in/",
    officialInfoUrl: "https://pmjay.gov.in/",
    tollFree: "14555",
    isVerified: true,
  },
  {
    id: "sch-002",
    name: "Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY)",
    fullName: "Maharashtra State Health Assurance Scheme",
    category: "State Universal Health Scheme",
    maxCoverage: "₹5,00,000 per family per year",
    eligibilitySummary: "All families holding Yellow, Orange, or White Ration Cards in Maharashtra.",
    coveredTreatments: "996 medical and surgical procedures across 30 identified specialties.",
    documentsRequired: ["Aadhaar Card", "Ration Card", "Doctor Referral Note"],
    howToApply: "Contact Aarogyamitra at any verified government or empaneled private hospital, or visit Jeevandayee portal.",
    portalUrl: "https://www.jeevandayee.gov.in/",
    officialInfoUrl: "https://arogya.maharashtra.gov.in/",
    tollFree: "155388 / 18002332200",
    isVerified: true,
  },
  {
    id: "sch-003",
    name: "Janani Shishu Suraksha Karyakram (JSSK)",
    fullName: "Maternal and Neonatal Health Protection Scheme",
    category: "Maternal & Child Health",
    maxCoverage: "100% Free institutional delivery, medicines, food and transport",
    eligibilitySummary: "All pregnant women delivering in public health institutions and sick newborns up to 1 year.",
    coveredTreatments: "Free C-section, blood transfusion, diagnostics, and free transport from home to PHC/hospital.",
    documentsRequired: ["Mother-Child Protection (MCP) Card", "Aadhaar Card"],
    howToApply: "Automatically activated at any PHC, Sub-District Hospital, or District Civil Hospital.",
    portalUrl: "https://nhm.gov.in/index1.php?lang=1&level=2&sublinkid=822&lid=219",
    officialInfoUrl: "https://nhm.gov.in/",
    tollFree: "102",
    isVerified: true,
  },
  {
    id: "sch-004",
    name: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    fullName: "Direct Benefit Transfer for Maternal Nutrition",
    category: "Maternal Health & Direct Benefit",
    maxCoverage: "₹5,000 to ₹6,000 Direct Cash Benefit into Bank Account",
    eligibilitySummary: "Pregnant women and lactating mothers for first living child (and second child if female).",
    coveredTreatments: "Wage-loss compensation, antenatal care registration, and infant immunization incentives.",
    documentsRequired: ["Aadhaar Card (Mother & Husband)", "MCP Card", "Bank Account linked with Aadhaar"],
    howToApply: "Register via local ASHA/Anganwadi worker or apply online on PMMVY official portal.",
    portalUrl: "https://pmmvy.wcd.gov.in/",
    officialInfoUrl: "https://wcd.nic.in/",
    tollFree: "104",
    isVerified: true,
  },
  {
    id: "sch-005",
    name: "Nikshay (National TB Elimination Programme)",
    fullName: "Direct Benefit Transfer & Free TB Treatment Scheme",
    category: "Infectious Disease Care",
    maxCoverage: "100% Free Diagnostic Tests, Anti-TB Drugs & ₹500/month Nutrition Support",
    eligibilitySummary: "All citizens diagnosed with Tuberculosis across India.",
    coveredTreatments: "Free CBNAAT/TrueNat testing, complete course of antitubercular medications, and direct nutritional cash support.",
    documentsRequired: ["Aadhaar Card", "Bank Passbook", "Sputum Test Report from PHC"],
    howToApply: "Enrolled automatically at any Government PHC or directly at Nikshay Web Portal.",
    portalUrl: "https://www.nikshay.in/",
    officialInfoUrl: "https://tbcindia.gov.in/",
    tollFree: "1800-11-6666",
    isVerified: true,
  },
];

export const mockNGOs = [
  {
    id: "ngo-001",
    name: "Gramin Arogya Sahayog Trust",
    focusArea: "Patient Transport & Food Support",
    district: "Gadchiroli & Chandrapur",
    services: [
      "Subsidized rural ambulance & transit to District Hospital",
      "Free meal tokens for accompanying patient attendants",
      "Emergency medicine micro-grants up to ₹5,000",
    ],
    contactPerson: "Sunita Gavit (Coordinator)",
    phone: "+91 94228 71923",
    address: "Near ITI Ground, Ashti Road, Gadchiroli",
    isVerified: true,
  },
  {
    id: "ngo-002",
    name: "Arogya Maitri Foundation",
    focusArea: "Tribal Health Outreach & Diagnostic Camps",
    district: "Vidarbha Region",
    services: [
      "Free monthly mobile echocardiogram and cardiac screening",
      "Assistance with Ayushman Bharat documentation",
      "Post-operative follow-up medicines support",
    ],
    contactPerson: "Dr. Arvind Pathak",
    phone: "+91 98901 33412",
    address: "Shivaji Nagar, Nagpur",
    isVerified: true,
  },
];

export const mockMedicinesInventory = [
  {
    id: "med-001",
    name: "Amlodipine Tablets 5mg",
    category: "Cardiovascular / Antihypertensive",
    currentStock: 120,
    unit: "tablets",
    averageDailyUsage: 35,
    daysOfSupplyLeft: 3.4,
    status: "critical",
    minimumThreshold: 300,
    lastRestocked: "2026-08-01",
    supplier: "State Medical Supplies Corporation",
  },
  {
    id: "med-002",
    name: "Paracetamol Tablets 500mg",
    category: "Analgesic / Antipyretic",
    currentStock: 1450,
    unit: "tablets",
    averageDailyUsage: 65,
    daysOfSupplyLeft: 22.3,
    status: "sufficient",
    minimumThreshold: 400,
    lastRestocked: "2026-08-12",
    supplier: "District Health Warehouse",
  },
  {
    id: "med-003",
    name: "Amoxicillin Capsules 500mg",
    category: "Antibiotic",
    currentStock: 180,
    unit: "capsules",
    averageDailyUsage: 40,
    daysOfSupplyLeft: 4.5,
    status: "depleting",
    minimumThreshold: 250,
    lastRestocked: "2026-08-05",
    supplier: "State Medical Supplies Corporation",
  },
  {
    id: "med-004",
    name: "Iron & Folic Acid (IFA) Tablets",
    category: "Maternal Nutrition",
    currentStock: 80,
    unit: "tablets",
    averageDailyUsage: 50,
    daysOfSupplyLeft: 1.6,
    status: "critical",
    minimumThreshold: 500,
    lastRestocked: "2026-07-28",
    supplier: "National Health Mission Supply",
  },
  {
    id: "med-005",
    name: "Oral Rehydration Salts (ORS) Sachets",
    category: "Gastrointestinal",
    currentStock: 620,
    unit: "sachets",
    averageDailyUsage: 25,
    daysOfSupplyLeft: 24.8,
    status: "sufficient",
    minimumThreshold: 150,
    lastRestocked: "2026-08-14",
    supplier: "District Health Warehouse",
  },
  {
    id: "med-006",
    name: "Metformin Tablets 500mg",
    category: "Antidiabetic",
    currentStock: 0,
    unit: "tablets",
    averageDailyUsage: 30,
    daysOfSupplyLeft: 0,
    status: "out_of_stock",
    minimumThreshold: 200,
    lastRestocked: "2026-07-15",
    supplier: "State Medical Supplies Corporation",
  },
];

export const mockAiRecommendations = [
  {
    id: "rec-001",
    caseId: "JVS-MH-7A82K1",
    patientNeedSummary: "Hypertension with suspected ischemic cardiac symptoms requiring secondary cardiology workup.",
    recommendations: [
      {
        type: "facility",
        title: "District Civil Hospital Gadchiroli - Cardiology OPD",
        matchScore: "95% Match",
        reason: "Closest facility (24.5 km) equipped with active 24x7 ICU, Echo diagnostics, and verified PM-JAY desk.",
        resourceId: "hosp-001",
      },
      {
        type: "scheme",
        title: "Ayushman Bharat PM-JAY & MJPJAY Coverage",
        matchScore: "Eligible",
        reason: "Patient's BPL/Ration card qualifies for 100% cashless diagnostic tests and inpatient cardiac care.",
        resourceId: "sch-001",
      },
      {
        type: "assistance",
        title: "Gramin Arogya Sahayog Transport Aid",
        matchScore: "Available",
        reason: "Provides local patient van assistance from Ashti to Gadchiroli Civil Hospital.",
        resourceId: "ngo-001",
      },
    ],
    nextSteps: [
      "Confirm referral with Dr. Ananya Deshmukh at Ashti PHC.",
      "Bring Aadhaar card and Ration card to the District Hospital Ayushman Mitra counter.",
      "Call Gramin Arogya Sahayog at +91 94228 71923 for travel coordination if required.",
    ],
    safetyCaution: "This is an AI-assisted coordination recommendation grounded strictly in verified facilities. It is not a medical diagnosis or prescription.",
    generatedAt: "2026-08-20T10:15:00Z",
  },
];

export const mockAdminAlerts = [
  {
    id: "alt-001",
    type: "inventory_depletion",
    severity: "critical",
    facility: "Ashti PHC (Gadchiroli)",
    title: "Critical Depletion: IFA & Metformin Stock",
    message: "Iron & Folic Acid (1.6 days left) and Metformin (0 stock). Urgent restock transfer recommended from Chamorshi sub-depot.",
    createdAt: "2026-08-22T08:00:00Z",
    status: "unresolved",
  },
  {
    id: "alt-002",
    type: "referral_bottleneck",
    severity: "warning",
    facility: "Sub-District Hospital Ballarpur",
    title: "Referral Intake Backlog (4 pending > 24 hrs)",
    message: "4 incoming obstetric referrals pending status confirmation beyond SLA threshold.",
    createdAt: "2026-08-21T17:30:00Z",
    status: "in_review",
  },
  {
    id: "alt-003",
    type: "service_anomaly",
    severity: "info",
    facility: "Dhanora Rural PHC",
    title: "Service Activity Variance Flag",
    message: "Doctor check-in recorded 45 minutes later than weekly baseline. Flagged for standard administrative review.",
    createdAt: "2026-08-22T10:00:00Z",
    status: "review_flag_only",
  },
];

export const mockDailyPhcMetrics = {
  totalVisitsToday: 38,
  activeCasesUnderFollowup: 14,
  criticalStockItemsCount: 3,
  pendingOutgoingReferrals: 2,
  doctorOnDuty: {
    name: "Dr. Ananya Deshmukh",
    checkedInAt: "08:45 AM",
    status: "Active / On Duty",
  },
};

/**
 * Educational Terminology Glossary for Safe Document Explanation
 * Strictly informational explanation of medical terms in everyday language.
 */
export const mockDocumentTermsGlossary = [
  {
    term: "Hb (Hemoglobin) 7.2 g/dL",
    category: "Blood Test / CBC",
    plainLanguageExplanation: "Hemoglobin measures the oxygen-carrying red protein in your blood. A value of 7.2 g/dL indicates severe anemia (low blood count).",
    whatDoctorUsuallyChecks: "Doctors typically evaluate iron deficiency, dietary intake, or recommend iron therapy/transfusion during pregnancy.",
    safetyNote: "This explanation is educational. Your PHC medical officer will decide the exact medicine or iron drip required.",
  },
  {
    term: "Blood Pressure 154/98 mmHg",
    category: "Vitals",
    plainLanguageExplanation: "The top number (systolic 154) and bottom number (diastolic 98) show the pressure in your blood vessels. This is higher than normal (hypertension).",
    whatDoctorUsuallyChecks: "Doctors check for regular salt reduction, daily tablet adherence, and order basic kidney/cardiac checks.",
    safetyNote: "Never change or stop hypertension medicines on your own without a doctor's advice.",
  },
  {
    term: "Echocardiogram (2D Echo)",
    category: "Diagnostic Test",
    plainLanguageExplanation: "A safe, painless ultrasound scan that creates live moving pictures of the heart valves and pumping chambers.",
    whatDoctorUsuallyChecks: "Helps cardiac specialists check how well heart muscles are pumping blood.",
    safetyNote: "Diagnostic ultrasound procedures must be interpreted by qualified radiologists or cardiologists.",
  },
  {
    term: "Serum Creatinine 2.4 mg/dL",
    category: "Kidney Function Test (KFT)",
    plainLanguageExplanation: "Creatinine is a natural waste product filtered by the kidneys. Elevated levels indicate the kidneys may need medical evaluation.",
    whatDoctorUsuallyChecks: "Doctors investigate hydration levels, blood pressure control, and may refer to a nephrologist.",
    safetyNote: "Consult a physician at your Community Health Centre or District Hospital for appropriate clinical testing.",
  },
];
